language: python
python: 2.7

env:
    - TOX_ENV=py26-twlatest
    - TOX_ENV=py26-twtrunk
    - TOX_ENV=py26-tw151
    - TOX_ENV=py26-tw150
    - TOX_ENV=py26-tw140
    - TOX_ENV=py26-tw132
    - TOX_ENV=py26-tw131
    - TOX_ENV=py26-tw130
    - TOX_ENV=py26-tw123
    - TOX_ENV=py26-tw122
    - TOX_ENV=py26-tw121
    - TOX_ENV=py27-twlatest
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=py27-tw151
    - TOX_ENV=py27-tw150
    - TOX_ENV=py27-tw140
    - TOX_ENV=py27-tw132
    - TOX_ENV=py27-tw131
    - TOX_ENV=py27-tw130
    - TOX_ENV=py27-tw123
    - TOX_ENV=py27-tw122
    - TOX_ENV=py27-tw121
    - TOX_ENV=pypy-twlatest
    - TOX_ENV=pypy-twtrunk
    - TOX_ENV=pypy-tw151
    - TOX_ENV=pypy-tw150
    - TOX_ENV=pypy-tw140
    - TOX_ENV=pypy-tw132
    - TOX_ENV=pypy-tw131
    - TOX_ENV=pypy-tw130
    - TOX_ENV=pypy-tw123
    - TOX_ENV=pypy-tw122
    - TOX_ENV=pypy-tw121
    - TOX_ENV=pyflakes
    - TOX_ENV=manifest

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=pyflakes

before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
  - "mongod --version"

install:
  - pip install tox coveralls

before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"

script:
  - tox -e $TOX_ENV

after_success:
    - coveralls

notifications:
    email: false
